#------------------- ALS Arpette config -------------------#

# Input files / directories
OUTPUT_DIR: "/Users/romain/Desktop/EPFL/PDM/Patch_extractor_v2/Output/Arpette/"
LAS_DIR: "/Users/romain/Desktop/EPFL/PDM/Patch_extractor_v2/Data/Arpette/ARPETTE_LV95_HELL_1560II_CH1_211020_{flight_id}.laz"

# Grid (Generic)
GRID_RES: 10     # Grid resolution [m]
GRID_BUFFER: 0   # Buffer around point cloud bounds [m]

# Patch generation  
PAIR_MODE: "successive" # Options: "successive", "all". Successive: only generate patches from successive lines. All: generate patches from all lines.
PATCH_DIMS: [500, 500, 1000] # [length, width, height] [m]

# Footprint
POINTCLOUD_DOWNSAMPLING: 100 # Take 1 point every N points to compute the footprint

# Extraction (minimal pipeline)
EXTRACTION_MODE: "independent" # Options: "independent". Extract all patches independently.

# LiMatch (optional)
LIMATCH_CMD: "" # Command to run LiMatch after extraction (e.g., "python -m limatch --input $PATCH_OUTPUT_DIR")
LIMATCH_CWD: "" # Working directory for LiMatch (e.g., "LiMatch")
