#------------------- ALS Arpette config -------------------#
# Scanning mode: ALS or MLS supported 
SCAN_MODE: "ALS"     # difference in patching method and GUI
# Project name
PRJ_NAME: "Arpette"

# Input files / directories
OUTPUT_DIR: "./output/Arpette/" 
PC_DIR: "./data/Arpette/ARPETTE_LV95_HELL_1560II_CH1_211020_{flight_id}"

OUTPUT_PC_FMT: "txt" # Point cloud extraction format | "laz" | "las" | "txt" | "txyzs" |

# Grid (Generic)
GRID_RES: 25     # Grid resolution [m]
GRID_BUFFER: 0   # Buffer around point cloud bounds [m]

# Patch generation  
PAIR_MODE: "successive" # Options: "successive", "all". Successive: only generate patches from successive lines. All: generate patches from all lines.
PATCH_DIMS: [500, 500, 1000] # [length, width, height] [m]

# Footprint
POINTCLOUD_DOWNSAMPLING: 100 # Take 1 point every N points to compute the footprint

# Extraction (minimal pipeline)
EXTRACTION_MODE: "independent" # Options: "independent". Extract all patches independently.

# LiMatch
LIMATCH_CFG: "/home/b085164/PDM_Romain_Defferrard/ESO-PDM/ALS/submodules/limatch/configs/ALS_close_range.yml" 
