#------------------- ALS Arpette config -------------------#

# Input files / directories
TRAJECTORY_PATH: "Data/Arpette/trajectory.txt"
DTM_PATH: "Data/epsg2056_raster.tif"
OUTPUT_DIR: "Output/Arpette/"
LAS_DIR: "Data/Arpette/ARPETTE_LV95_HELL_1560II_CH1_211020_{flight_id}.laz" # Channel CH1 ou CH2
LOG_DIR: "Data/Arpette/timestamps/211020_{flight_id}_Channel_1.sdc.log" # GPS timestamps for start/end of each flight line

# Footprint mode 
FOOTPRINT_MODE: "Generic" # Options: "Generic", "SwissDTM"

# Flight loading 
DAY_OF_WEEK: 3 
TRAJECTORY_COLUMNS: ["gps_time", "lon", "lat", "alt", "roll", "pitch", "yaw", "_"]

# Grid (Generic)
GRID_RES: 10     # Grid resolution [m]
GRID_BUFFER: 0   # Buffer around point cloud bounds [m]

# DTM (SwissDTM)
RASTER_BUFFER: 1000 # Buffer for raster generation around min/max North/East [m]

# Lidar scanning mode (SwissDTM)
LIDAR_SCAN_MODE: "right"  # Options: "across", "left", "right" (right for Channel_1)
LIDAR_TILT_ANGLE: 14      # [deg]: "Vallet"-> 0, "Arpette"-> 14
LIDAR_FOV: 60             # [deg]: "Vallet"-> 75, "Arpette"-> 60

# Patch generation  
PAIR_MODE: "successive" # Options: "successive", "all". Successive: only generate patches from successive lines. All: generate patches from all lines.
PATCH_DIMS: [500, 500, 1000] # [length, width, height] [m]

# Footprint
FLIGHT_DOWNSAMPLING: 100 # (SwissDTM) Take a flight position every X coordinates in trajectory
POINTCLOUD_DOWNSAMPLING: 100 # Take 1 point every N points to compute the footprint

# Extraction
EXTRACTION_MODE: "independent" # Options: "binary", "Extra_Bytes", "independent". independent: extract all patches independently. Extra_Bytes: write extra bytes in the .laz 
