#------------------- MLS Epalinges config -------------------#

# Scanning mode: ALS or MLS supported 
SCAN_MODE: "MLS"     # difference in patching method and GUI
# Project name
PRJ_NAME: "SAM_Epalinges"

# Input files / directories
OUTPUT_DIR: "/home/b085164/PDM_Romain_Defferrard/ESO-PDM/ALS/output/SAM_Epalinges/" 
# PC: "/home/b085164/PDM_Romain_Defferrard/ESO-PDM/ALS/output/Arpette/" 
# RD: "/Users/romain/Desktop/EPFL/PDM/ESO-PDM/ALS/output"
LAS_DIR: "/home/b085164/PDM_Romain_Defferrard/ESO-PDM/ALS/data/SAM/Epalinges_{flight_id}_merged.las"
# PC: "/home/b085164/PDM_Romain_Defferrard/ESO-PDM/ALS/data/Arpette/ARPETTE_LV95_HELL_1560II_CH1_211020_{flight_id}.laz"
# RD: "/Users/romain/Desktop/EPFL/PDM/ESO-PDM/ALS/data/Arpette"

# Grid (Generic)
GRID_RES: 1     # Grid resolution [m]
GRID_BUFFER: 0   # Buffer around point cloud bounds [m]

# Patch generation  
PAIR_MODE: "all" # Options: "successive", "all". Successive: only generate patches from successive lines. All: generate patches from all lines.
#PATCH_DIMS: [500, 500, 1000] # [length, width, height] [m]

# Footprint
POINTCLOUD_DOWNSAMPLING: 1 # Take 1 point every N points to compute the footprint

# Extraction (minimal pipeline)
EXTRACTION_MODE: "independent" # Options: "independent". Extract all patches independently.

# LiMatch
LIMATCH_CFG: "/home/b085164/PDM_Romain_Defferrard/ESO-PDM/ALS/submodules/limatch/configs/MLS.yml" 

# GUI
CRS: "EPSG:2056"     # (Optionnal) Spatial reference system