#------------------- ALS Vallet 2020 config -------------------#

# Input files / directories
OUTPUT_DIR: "Output/Vallet/test_1"
LAS_DIR: "Data/Vallet2020/ALS_line{flight_id}.txt"

# Grid (Generic)
GRID_RES: 25     # Grid resolution [m]
GRID_BUFFER: 0   # Buffer around point cloud bounds [m]

# Patch generation  
PAIR_MODE: "successive" # Options: "successive", "all". Successive: only generate patches from successive lines. All: generate patches from all lines.
PATCH_DIMS: [100, 150, 400] # [length, width, height] [m]

# Footprint
POINTCLOUD_DOWNSAMPLING: 100 # (Generic) Take 1 point every N points to compute the footprint

# Extraction
EXTRACTION_MODE: "independent" # Options: "independent". Extract all patches independently.

# LiMatch (optional)
LIMATCH_CMD: "" # Command to run LiMatch after extraction (e.g., "python -m limatch --input $PATCH_OUTPUT_DIR")
LIMATCH_CWD: "" # Working directory for LiMatch (e.g., "LiMatch")
